import { StyleProp, TextStyle } from 'react-native'

export const image: StyleProp<TextStyle>
export const art: StyleProp<TextStyle>
export const deplacer: StyleProp<TextStyle>
export const rest: StyleProp<TextStyle>
export const il: StyleProp<TextStyle>
export const bn: StyleProp<TextStyle>
export const ecrit: StyleProp<TextStyle>
export const teste: StyleProp<TextStyle>
export const img: StyleProp<TextStyle>
export const detail: StyleProp<TextStyle>
export const overlay: StyleProp<TextStyle>
export const popup: StyleProp<TextStyle>
export const btnClose: StyleProp<TextStyle>
export const menu: StyleProp<TextStyle>
export const menu-title: StyleProp<TextStyle>
export const menu-title:before: StyleProp<TextStyle>
export const menu-title:hover: StyleProp<TextStyle>
export const menu-title:hover:before: StyleProp<TextStyle>
export const menu:hover>menu-title:before: StyleProp<TextStyle>
export const menu-title:after: StyleProp<TextStyle>
export const menu:hover>menu-title:after: StyleProp<TextStyle>
export const menu-title_2nd: StyleProp<TextStyle>
export const menu-title_2nd:hover: StyleProp<TextStyle>
export const menu-title_2nd:before: StyleProp<TextStyle>
export const menu-title_2nd:hover:before: StyleProp<TextStyle>
export const menu-title_3rd: StyleProp<TextStyle>
export const menu-title_3rd:hover: StyleProp<TextStyle>
export const menu-title_3rd:before: StyleProp<TextStyle>
export const menu-title_3rd:hover:before: StyleProp<TextStyle>
export const menu-title_4th: StyleProp<TextStyle>
export const menu-title_4th:hover: StyleProp<TextStyle>
export const menu-title_4th:before: StyleProp<TextStyle>
export const menu-title_4th:hover:before: StyleProp<TextStyle>
export const menu-dropdown: StyleProp<TextStyle>
export const menu-dropdown:after: StyleProp<TextStyle>
export const menu:not(:hover)>menu-dropdown: StyleProp<TextStyle>
export const menu:not(:hover)>menu-dropdown:after: StyleProp<TextStyle>
export const menu:not(:hover)>menu-title:after: StyleProp<TextStyle>
export const menu-dropdown>*: StyleProp<TextStyle>
export const menu-dropdown>*:hover: StyleProp<TextStyle>
export const menu:not(:hover)>menu-dropdown>*: StyleProp<TextStyle>
export const dep: StyleProp<TextStyle>
export const dest: StyleProp<TextStyle>
export const dis: StyleProp<TextStyle>
export const dev: StyleProp<TextStyle>
export const footer: StyleProp<TextStyle>
export const nomBurger: StyleProp<TextStyle>
export const prix: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const ajout: StyleProp<TextStyle>
export const add: StyleProp<TextStyle>
export const style: StyleProp<TextStyle>
export const header-intro: StyleProp<TextStyle>
export const t-center: StyleProp<TextStyle>
export const p-b-158: StyleProp<TextStyle>
export const p-t-135: StyleProp<TextStyle>
export const p-t-30: StyleProp<TextStyle>
export const col-md-4: StyleProp<TextStyle>
export const p-t-35: StyleProp<TextStyle>
export const hov-img-zoom: StyleProp<TextStyle>
export const bo-rad-10: StyleProp<TextStyle>
export const txt5: StyleProp<TextStyle>
export const trans-0-4: StyleProp<TextStyle>
export const m-b-13: StyleProp<TextStyle>
export const m-b-20: StyleProp<TextStyle>
export const fa-long-arrow-right:before: StyleProp<TextStyle>
export const hp: StyleProp<TextStyle>
export const ig: StyleProp<TextStyle>
